// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmF7QSbgsM7RYCnipShiu8ouR_RPkF9hg',
    appId: '1:46863159285:web:b1cd8e2034edde562adabc',
    messagingSenderId: '46863159285',
    projectId: 'flutterlab-firebase-7a855',
    authDomain: 'flutterlab-firebase-7a855.firebaseapp.com',
    storageBucket: 'flutterlab-firebase-7a855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxcIWMX7PXg-VnHVnIJdZIbA0C4Flwvy8',
    appId: '1:46863159285:android:46c7b8172811ed1f2adabc',
    messagingSenderId: '46863159285',
    projectId: 'flutterlab-firebase-7a855',
    storageBucket: 'flutterlab-firebase-7a855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_L0UsB6fIPuzyzheNswr_fjmnoAecGY',
    appId: '1:46863159285:ios:affe09d1b31647b32adabc',
    messagingSenderId: '46863159285',
    projectId: 'flutterlab-firebase-7a855',
    storageBucket: 'flutterlab-firebase-7a855.appspot.com',
    iosClientId: '46863159285-l8bikuma93fq3po5j49unfr84j3oaij9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_L0UsB6fIPuzyzheNswr_fjmnoAecGY',
    appId: '1:46863159285:ios:affe09d1b31647b32adabc',
    messagingSenderId: '46863159285',
    projectId: 'flutterlab-firebase-7a855',
    storageBucket: 'flutterlab-firebase-7a855.appspot.com',
    iosClientId: '46863159285-l8bikuma93fq3po5j49unfr84j3oaij9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebase',
  );
}
